[project]
name = "rsgi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "granian>=2.6.1",
    "jinja2>=3.1",
    "pydantic>=2.12.5",
]

[build-system]
requires = ["setuptools>=69.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["rsgi*"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
